name: run on ubuntu
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - uses: actions/upload-artifact@v3
          with:
            name: report
            path: reports/html/
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: print event name
        if: ${{github.env === 'workflow_dispatch'}}
        run: |
          echo $GITHUB_EVENT_NAME
